### ISSUE TITLE
Maquetar la página de inicio

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/http-app-front#15]
Debe contener:
- [x] Header
- [x] Componente Usage
- [x] Componte de búsqueda (Search)
- [x] Componente de filtrado
- [x] Cards de los códigos HTTP
- [x] Footer

Tener en cuenta:
- [x] Reutilización de componentes
- [x] Diseño responsive

**Comment by TiagoBG** [comment]
Home page styles and layout details fixed
