### ISSUE TITLE
Maquetar componente de búsqueda

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/http-app-front#3]
Tener en cuenta:
- [x] Se puede filtrar en tiempo real
- [x] Al dar enter te redirige a la página con descripción o 404 si no existe el código
- [x] Hacer una validación antes de enviar los códigos de búsqueda

**Comment by TiagoBG** [comment]
Search bar component uses real time filter and validation. If code is correct it navigates to the custom code page.

**Comment by TiagoBG** [comment]
Conflicts resolved and merged with usage feature
